<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\TmbdApi\TmbdApi.csproj" />
      <ProjectReference Include="..\VideoTrackerServer.Domain\VideoTrackerServer.Domain.csproj" />
      <ProjectReference Include="..\VideoTrackerServer.Repositories\VideoTrackerServer.Repositories.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.Extensions.Options" Version="11.0.0-rc.1.26425.128" />
    </ItemGroup>

</Project>
